#!/bin/sh
RETVAL=0

start() {
	nohup /root/gifserver/gifserver.py &
}

stop() {
	echo "Nothing to do"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status $processname
		RETVAL=$?
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|status|restart}"
		;;
esac
exit $RETVAL
